name: Weather Cron Job

on:
  schedule:
    - cron: '*/15 * * * *'  # runs every 15 minutes
  workflow_dispatch:        # allows manual runs too

jobs:
  run-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather script
        run: python workflows/workflow.py
        env:
          LATITUDE: '39.02206'
          LONGITUDE: '-94.8478'

      - name: Commit and push updated complication JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add workflows/output.json
          git diff --cached --quiet || git commit -m "Update complication output.json [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
